"use client";

import Link from "next/link";
import {useMemo,useState} from "react";
import {expertCases,managedOutbreaks} from "@/features/expert/data";

const outbreakMap="https://lh3.googleusercontent.com/aida-public/AB6AXuCQwo4RnuoJsy6Pgnx9RTBfb84eYxYJXTirBx0v7x1_587wz3Byr0ruDAaZLZlC5cZIsPN5ux7diDnKUN5aslkDJtoWTCJ6iJ8LMu_uY8Kg8S8f4Ie58CEmcPfXZjbuo0sVvIMROI06-distEu8lcf3o26hDeW0YjQongLPCeR_hMF0BEJsKSqJawFPwgpZpPpQqTrsCPdNfOpTFcR2ZBWa4f_osBJGfQbBw7CuuUEN-1h6LcD9kbmr";

export function ExpertDashboard(){
 const [filter,setFilter]=useState<"all"|"urgent"|"low-confidence">("all");
 const cases=useMemo(()=>expertCases.filter(item=>filter==="all"||filter==="urgent"?filter==="all"||item.priority==="urgent":item.confidence<.7),[filter]);
 function exportCases(){const rows=["Case,Farmer,District,Crop,Prediction,Confidence,Severity,Status",...cases.map(c=>`${c.id},${c.farmerName},${c.district},${c.crop},${c.aiSuggestion},${Math.round(c.confidence*100)}%,${c.severity},${c.status}`)];const url=URL.createObjectURL(new Blob([rows.join("\n")],{type:"text/csv"}));const a=document.createElement("a");a.href=url;a.download="expert-priority-cases.csv";a.click();URL.revokeObjectURL(url)}
 return <div className="mx-auto max-w-[1240px] space-y-4 px-4 py-5 md:px-6 md:py-7">
  <section className="grid grid-cols-2 gap-3 md:grid-cols-5"><Metric icon="▣" label="New Cases" value="18" note="+4 from last hour"/><Metric icon="!" label="Urgent" value="5" note="Action Required" danger/><Metric icon="?" label="Low Confidence" value="7" note="Review Required" warning/><Metric icon="◉" label="Outbreaks" value="3" note="Active Clusters"/><Metric icon="◷" label="Avg Response" value="42 min" note="Goal: under 60 min"/></section>
  <section className="overflow-hidden rounded-2xl border border-brand/10 bg-white shadow-sm"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-5 py-4"><div><h1 className="text-lg font-extrabold text-brand-dark">Priority Case Queue</h1><p className="mt-1 text-[9px] text-muted">Sorted by severity, confidence and waiting time</p></div><div className="flex gap-2"><select value={filter} onChange={e=>setFilter(e.target.value as typeof filter)} aria-label="Filter priority cases" className="h-9 rounded-lg border border-border bg-white px-3 text-[9px] font-bold"><option value="all">All cases</option><option value="urgent">Urgent</option><option value="low-confidence">Low confidence</option></select><button onClick={exportCases} className="h-9 rounded-lg border border-border px-3 text-[9px] font-bold">⇩ Export</button></div></header><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead className="bg-[#eef4ff] text-[8px] font-extrabold uppercase tracking-wide text-muted"><tr><th className="px-5 py-3">Case ID</th><th className="px-4 py-3">Farmer &amp; District</th><th className="px-4 py-3">Crop</th><th className="px-4 py-3">AI Prediction</th><th className="px-4 py-3">Confidence</th><th className="px-4 py-3">Severity</th><th className="px-4 py-3">Submitted</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Action</th></tr></thead><tbody>{cases.map((item,index)=><CaseRow key={item.id} item={item} index={index}/>)}</tbody></table></div><footer className="flex items-center justify-between border-t border-border bg-[#eef4ff] px-5 py-3 text-[9px] font-bold text-muted"><span>Showing {cases.length} of 18 new cases</span><span className="text-base">‹ &nbsp; ›</span></footer></section>
  <section className="grid items-stretch gap-3 lg:grid-cols-[minmax(0,2.35fr)_minmax(220px,.85fr)]">
   <article className="flex min-h-[385px] flex-col rounded-xl border border-brand/10 bg-white p-4 shadow-sm"><header className="flex items-start justify-between gap-3"><div><h2 className="text-sm font-extrabold text-brand-dark">Live Outbreak Monitor</h2><p className="mt-0.5 text-[8px] text-muted">Geospatial analysis of active pest clusters</p></div><span className="flex items-center gap-1 text-[8px] font-bold text-success"><span className="size-2 rounded-full bg-[#95d4b2]"/>Live Tracking</span></header><div className="relative mt-3 min-h-0 flex-1 overflow-hidden rounded-lg border border-border bg-cover bg-center" style={{backgroundImage:`url(${outbreakMap})`}} role="img" aria-label="Approximate outbreak clusters across Punjab"><div className="absolute inset-0 bg-[#d9e8df]/15"/><div className="absolute left-3 top-3 z-10 rounded-lg border border-brand/10 bg-white/90 p-2.5 shadow-md backdrop-blur"><p className="text-[7px] font-extrabold uppercase tracking-wide text-muted">Cluster Hotspots</p><p className="mt-2 text-[8px] font-bold"><span className="mr-1 text-danger">●</span>Sahiwal (High)</p><p className="mt-1 text-[8px] font-bold"><span className="mr-1 text-amber-700">●</span>Multan (Increasing)</p></div>{managedOutbreaks.map((item,index)=><Link key={item.id} href={`/expert/outbreaks?cluster=${item.id}`} style={{left:`${50+index*21}%`,top:`${48+index*15}%`}} className={`absolute z-10 grid size-4 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border-2 border-white shadow-xl ${item.status==="confirmed"?"bg-danger ring-[12px] ring-red-500/20":"bg-amber-600 ring-[10px] ring-amber-500/15"}`} aria-label={`${item.disease}, ${item.district}, ${item.reports} reports`}/>)}</div></article>
   <aside className="flex min-h-[385px] flex-col rounded-xl border border-brand/10 bg-white p-4 shadow-sm">
    <h2 className="text-sm font-extrabold text-brand-dark">AI Health Check</h2>
    <div className="mt-3 rounded-xl border border-brand/10 bg-[#edf6e9] p-4">
     <p className="text-[8px] font-extrabold text-[#245113]">AI Model Accuracy</p>
     <div className="mt-2 flex items-baseline gap-2"><strong className="text-xl text-brand-dark">94.2%</strong><span className="text-[7px] text-muted">Global Precision</span></div>
     <div className="mt-3 h-1.5 rounded-full bg-white"><div className="h-full w-[94%] rounded-full bg-brand"/></div>
    </div>
    <div className="mt-3 rounded-xl border border-border bg-[#eef4ff] p-4">
     <p className="text-[8px] font-extrabold text-muted">Your Daily Reviews</p>
     <div className="mt-2 flex items-baseline gap-2"><strong className="text-xl">32</strong><span className="text-[7px] text-muted">/ 45 Target</span></div>
     <div className="mt-3 flex h-[58px] items-end gap-1.5">{[28,44,55,82,62,23,23].map((height,index)=><span key={index} className={`flex-1 ${index<5?"bg-brand":"bg-[#bfc9c1]"}`} style={{height:`${height}%`,opacity:index < 5 ? 0.25 + index * 0.18 : 1}}/>)}</div>
    </div>
    <Link href="/expert/reports" className="mt-auto flex min-h-11 items-center justify-center gap-2 rounded-xl bg-brand text-[9px] font-extrabold text-white"><span>AI</span>Train Custom Model</Link>
   </aside>
  </section>
  <Link href="/expert/cases" aria-label="Open case queue" className="fixed bottom-20 right-5 z-20 grid size-14 place-items-center rounded-2xl border-2 border-brand/20 bg-[#b9ee9e] text-2xl font-bold text-brand shadow-xl lg:bottom-7">+</Link>
 </div>
}
function Metric({icon,label,value,note,danger,warning}:{icon:string;label:string;value:string;note:string;danger?:boolean;warning?:boolean}){return <article className={`rounded-xl border bg-white p-4 shadow-sm ${danger?"border-l-4 border-l-danger":warning?"border-l-4 border-l-amber-700 bg-amber-50":"border-brand/10"}`}><div className="flex items-center justify-between"><p className="text-[9px] font-bold text-muted">{label}</p><span className={danger?"text-danger":warning?"text-amber-800":"text-brand"}>{icon}</span></div><p className={`mt-2 text-2xl font-extrabold ${danger?"text-danger":warning?"text-amber-800":"text-brand-dark"}`}>{value}</p><p className={`mt-1 text-[8px] font-bold ${danger?"text-danger":warning?"text-amber-800":"text-success"}`}>{note}</p></article>}
function CaseRow({item,index}:{item:(typeof expertCases)[number];index:number}){const confidence=Math.round(item.confidence*100);const urgent=item.priority==="urgent";return <tr className={`${urgent?"bg-red-50/40":index%2?"bg-white":"bg-slate-50/30"} border-t border-border text-[10px] hover:bg-[#eef4ff]`}><td className="px-5 py-4 font-extrabold text-brand">#{item.id}</td><td className="px-4 py-4"><strong className="block">{item.farmerName}</strong><span className="text-[8px] text-muted">{item.district}, PK</span></td><td className="px-4 py-4">{item.crop}</td><td className={`px-4 py-4 font-bold ${urgent?"text-danger":item.confidence<.7?"text-amber-800":"text-success"}`}>{item.aiSuggestion}</td><td className="px-4 py-4"><span className="block h-1.5 w-16 rounded-full bg-slate-200"><span className={`block h-full rounded-full ${urgent?"bg-danger":item.confidence<.7?"bg-amber-700":"bg-brand"}`} style={{width:`${confidence}%`}}/></span><b className="text-[8px]">{confidence}%</b></td><td className="px-4 py-4"><span className={`rounded px-2 py-1 text-[7px] font-extrabold uppercase ${item.severity==="high"?"bg-danger text-white":item.severity==="moderate"?"bg-[#b9ee9e] text-[#245113]":"bg-slate-200 text-muted"}`}>{item.severity}</span></td><td className="px-4 py-4 text-muted">{14+index*14} mins ago</td><td className={`px-4 py-4 font-bold ${urgent?"text-danger":item.confidence<.7?"text-amber-800":"text-muted"}`}>{urgent?"● Urgent":item.confidence<.7?"? AI Unsure":item.status.replaceAll("_"," ")}</td><td className="px-4 py-4"><Link href={`/expert/cases/${item.id}`} className="inline-flex min-h-8 items-center rounded-full bg-brand px-3 font-bold text-white">Review</Link></td></tr>}
