"use client";

import {useState} from "react";
import {managedOutbreaks} from "@/features/expert/data";

const mapImage="https://lh3.googleusercontent.com/aida-public/AB6AXuCsa6oeEflUElaMByIHsdCTBk8Q-mT5Ns314q9sl8_pdYbcyfoVH40WMCuA9YhEjEozFKED7FxUTu3Ysh_M0PKi_2cKedVGE8IQYSUhtZ4XjEarbu_XYOWJ5nDxFVAwpLJt5U8HDU8bnzBweiBqlv_BtxDEtcvge7MPcBoXoy-2hvdzF4GEqLl2h43-zxyNsL26abay-zD3LlGXbElPcJFZe19vqjatJOdSs9ntp20oE5hmgw_lmOFc";

export function OutbreakManagement(){
 const [selectedId,setSelectedId]=useState(managedOutbreaks[0].id);const [radius,setRadius]=useState(12.5);const [direction,setDirection]=useState("NE");const [action,setAction]=useState<string|null>(null);const [publishing,setPublishing]=useState(false);const [mapZoom,setMapZoom]=useState(1);const selected=managedOutbreaks.find(x=>x.id===selectedId)??managedOutbreaks[0];
 async function publish(){setPublishing(true);await new Promise(resolve=>setTimeout(resolve,700));setPublishing(false);setAction("Regional advisory prepared for 1,420 relevant farmers.")}
 return <div className="relative min-h-[calc(100dvh-4rem)] overflow-hidden bg-[#f8f4ea] xl:h-[calc(100dvh-4rem)]">
  <div className="grid min-h-[calc(100dvh-4rem)] xl:h-full xl:grid-cols-[minmax(0,1fr)_370px]">
   <section className="relative min-h-[620px] overflow-hidden bg-[#eef4ff]" aria-label="Privacy-protected outbreak management map">
    <div className="absolute inset-0 bg-cover bg-center grayscale-[25%] opacity-75 transition-transform duration-500 ease-out" style={{backgroundImage:`url(${mapImage})`,transform:`scale(${mapZoom})`}}/><div className="absolute inset-0 bg-[radial-gradient(circle_at_45%_45%,transparent_30%,rgba(238,244,255,.48)_100%)]"/>
    <div className="absolute left-5 top-5 z-20 flex items-center gap-3 rounded-2xl border border-white/70 bg-white/85 px-4 py-3 shadow-xl backdrop-blur-xl"><span className="grid size-9 place-items-center rounded-xl bg-brand text-[10px] font-extrabold text-white">LIVE</span><div><p className="text-[10px] font-extrabold text-brand-dark">Regional outbreak intelligence</p><p className="mt-0.5 text-[8px] text-muted">Updated just now · privacy-protected tiles</p></div></div>
    {managedOutbreaks.map((item,index)=>{const confirmed=item.status==="confirmed";return <button key={item.id} onClick={()=>setSelectedId(item.id)} style={{left:`${28+index*31}%`,top:`${31+index*25}%`}} className="group absolute z-10 -translate-x-1/2 -translate-y-1/2" aria-label={`Select ${item.disease} in ${item.district}`}><span className={`absolute inset-1 rounded-full ${confirmed?"bg-danger/15":"bg-amber-500/20"} ${selectedId===item.id?"scale-[7]":"scale-[4]"} transition-transform`}/><span className={`relative grid place-items-center rounded-full border-2 border-white font-extrabold text-white shadow-xl transition ${confirmed?"size-8 bg-danger":"size-6 bg-amber-800"} ${selectedId===item.id?"ring-8 ring-white/35":""}`}>{confirmed?"!":"!"}</span><span className="pointer-events-none absolute bottom-full left-1/2 mb-3 hidden w-44 -translate-x-1/2 rounded-xl border border-brand/10 bg-white p-3 text-left shadow-xl group-hover:block"><strong className={`block text-[9px] ${confirmed?"text-danger":"text-amber-800"}`}>{item.disease}</strong><small className="mt-1 block text-[8px] text-muted">{item.reports} anonymized reports · {item.district}</small></span></button>})}
    <div className="absolute bottom-5 left-5 z-20 rounded-2xl border border-brand/10 bg-white/90 p-4 shadow-xl backdrop-blur"><Legend color="bg-danger" label="Confirmed Zone"/><Legend color="bg-amber-700" label="Suspect Cluster"/><Legend color="bg-brand/30" label="Healthy Monitoring"/><p className="mt-3 border-t border-border pt-2 text-[7px] text-muted">Shielded · Regional data anonymized</p></div>
    <div className="absolute bottom-5 right-5 z-20 flex items-end gap-3"><div className="overflow-hidden rounded-xl border border-brand/10 bg-white/90 shadow-xl backdrop-blur"><button onClick={()=>setMapZoom(z=>Math.min(1.35,z+.08))} aria-label="Zoom map in" className="grid size-10 place-items-center border-b border-border text-base font-bold text-brand hover:bg-brand-soft">+</button><button onClick={()=>setMapZoom(z=>Math.max(1,z-.08))} aria-label="Zoom map out" className="grid size-10 place-items-center text-base font-bold text-brand hover:bg-brand-soft">-</button></div><button aria-label="Add outbreak cluster" className="grid size-12 place-items-center rounded-2xl bg-[#3c6929] text-2xl text-white shadow-[0_12px_30px_rgba(0,69,45,.28)] transition hover:-translate-y-1 hover:bg-brand">+</button></div>
   </section>
   <aside className="relative z-20 flex flex-col border-l border-brand/10 bg-[linear-gradient(180deg,rgba(255,255,255,.97),rgba(248,251,246,.96))] p-5 shadow-[-18px_0_45px_rgba(23,50,77,.08)] backdrop-blur-xl xl:overflow-y-auto"><header className="flex items-center justify-between"><div><p className="text-[7px] font-extrabold uppercase tracking-[.18em] text-success">Expert command centre</p><h1 className="mt-1 text-lg font-extrabold tracking-tight text-brand-dark">Outbreak Management</h1></div><button aria-label="More outbreak options" className="grid size-9 place-items-center rounded-full text-sm font-bold text-muted transition hover:bg-surface-soft hover:text-brand">...</button></header>
    <article className="mt-5 overflow-hidden rounded-2xl border border-brand/10 bg-white shadow-[0_10px_30px_rgba(23,50,77,.07)]"><div className="h-1 bg-gradient-to-r from-amber-500 via-amber-300 to-transparent"/><div className="p-4"><div className="flex items-start justify-between gap-3"><div><span className="rounded-full bg-amber-100 px-2.5 py-1 text-[7px] font-extrabold uppercase tracking-wide text-amber-900">Selected Cluster #{selected.id}</span><h2 className="mt-2 text-sm font-extrabold text-brand-dark">{selected.disease} {selected.status==="suspected"?"Suspect":"Cluster"}</h2><p className="mt-1 text-[8px] text-muted">Location: {selected.district} Region</p></div><div className="size-12 shrink-0 rounded-xl border-2 border-white bg-cover bg-center shadow-md" style={{backgroundImage:"url('/expert-case-leaf-early.png')"}} role="img" aria-label="Crop symptom evidence"/></div><dl className="mt-4 grid grid-cols-2 gap-3"><SmallMetric label="Growth Rate" value={`+${Math.round(selected.spreadRate*20)}% / day`} danger/><SmallMetric label="Reports" value={`${selected.reports} Active`}/></dl></div></article>
    <section className="mt-5"><h2 className="text-[8px] font-extrabold uppercase tracking-widest text-muted">Spread Simulation</h2><div className="mt-4"><label className="flex justify-between text-[8px] font-bold"><span>Alert Radius</span><output className="text-brand">{radius.toFixed(1)} KM</output></label><input type="range" min="2" max="25" step="0.5" value={radius} onChange={e=>setRadius(Number(e.target.value))} className="mt-2 w-full accent-brand"/></div><div className="mt-4"><div className="flex justify-between text-[8px] font-bold"><span>Spread Direction (Wind)</span><span className="text-brand">{direction==="NE"?"North East":direction}</span></div><div className="mt-2 grid grid-cols-5 gap-1 rounded-full border border-brand/10 bg-[#edf6e9] p-1">{["N","E","S","W","NE"].map(item=><button key={item} onClick={()=>setDirection(item)} className={`min-h-8 rounded-full text-[8px] font-extrabold ${direction===item?"bg-brand text-white shadow":"text-muted"}`}>{item}</button>)}</div></div></section>
    <section className="mt-5 border-t border-border pt-5"><h2 className="text-[8px] font-extrabold uppercase tracking-widest text-muted">Action Protocol</h2><div className="mt-3 space-y-2"><Action tone="danger" onClick={()=>setAction("Suspected cluster confirmed and queued for regional notification.")}>✓ Confirm Suspected Cluster</Action><Action onClick={()=>setAction("Cluster remains under observation. A review reminder was created.")}>◉ Keep Under Observation</Action><Action tone="primary" onClick={()=>void publish()}>{publishing?"Publishing advisory...":"▰ Publish Regional Advisory"}</Action></div></section>
    {action&&<div role="status" aria-live="polite" className="mt-4 flex items-start gap-2 rounded-xl border border-green-200 bg-green-50 p-3 text-[9px] leading-4 text-green-950 shadow-sm"><span className="font-extrabold">OK</span><span className="flex-1">{action}</span><button onClick={()=>setAction(null)} aria-label="Dismiss status" className="font-bold text-green-900">x</button></div>}
    <div className="mt-auto pt-5"><div className="flex gap-3 rounded-2xl border border-brand/10 bg-[#edf6e9] p-4 shadow-sm"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-white text-[9px] font-extrabold text-brand">SAFE</span><div><p className="text-[9px] font-extrabold text-brand">Privacy Mode Active</p><p className="mt-1 text-[8px] leading-4 text-muted">Exact coordinates are masked. Analysis uses aggregated regional tiles to protect farmer identity.</p></div></div></div>
   </aside>
  </div>
 </div>
}
function Legend({color,label}:{color:string;label:string}){return <div className="mb-2 flex items-center gap-2"><span className={`size-2.5 rounded-full ${color}`}/><span className="text-[8px] font-extrabold uppercase tracking-wide">{label}</span></div>}
function SmallMetric({label,value,danger}:{label:string;value:string;danger?:boolean}){return <div className="rounded-xl border border-brand/5 bg-[#f8f9ff] p-3"><dt className="text-[7px] uppercase text-muted">{label}</dt><dd className={`mt-1 text-[10px] font-extrabold ${danger?"text-danger":"text-brand"}`}>{value}</dd></div>}
function Action({children,tone,onClick}:{children:React.ReactNode;tone?:"danger"|"primary";onClick:()=>void}){return <button type="button" onClick={onClick} className={`min-h-11 w-full rounded-full px-4 text-[9px] font-extrabold transition active:scale-[.98] ${tone==="danger"?"bg-danger text-white shadow-md":tone==="primary"?"bg-brand text-white shadow-md":"border-2 border-brand bg-white text-brand"}`}>{children}</button>}
