import type { MigrationInterface, QueryRunner } from 'typeorm';
export class OfflineSync1755000018000 implements MigrationInterface {
  name = 'OfflineSync1755000018000';
  async up(q: QueryRunner): Promise<void> {
    await q.query(
      `CREATE TABLE mutation_receipts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES users(id)ON DELETE CASCADE,device_id uuid NOT NULL REFERENCES devices(id)ON DELETE CASCADE,client_mutation_id uuid NOT NULL,type varchar(32)NOT NULL,status varchar(16)NOT NULL,request_hash char(64)NOT NULL,result jsonb,conflict jsonb,error_code varchar(80),attempt_count integer NOT NULL DEFAULT 1,applied_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version integer NOT NULL DEFAULT 1,UNIQUE(user_id,device_id,client_mutation_id),CONSTRAINT ck_mutation_receipt_type CHECK(type IN('FIELD_INSPECTION','FOLLOW_UP_ANSWERS','CROP_SCAN_METADATA','TASK_COMPLETION','VOICE_NOTE_METADATA','COMMUNITY_REPORT')),CONSTRAINT ck_mutation_receipt_status CHECK(status IN('PROCESSING','APPLIED','CONFLICT','FAILED')));CREATE INDEX idx_mutation_receipts_user_created ON mutation_receipts(user_id,created_at DESC)`,
    );
    await q.query(
      `CREATE TABLE field_inspections(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES users(id)ON DELETE CASCADE,field_id uuid NOT NULL REFERENCES fields(id)ON DELETE CASCADE,notes text NOT NULL,observed_at timestamptz NOT NULL,media_asset_ids uuid[]NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version integer NOT NULL DEFAULT 1);CREATE INDEX idx_field_inspections_user_observed ON field_inspections(user_id,observed_at DESC)`,
    );
    await q.query(
      `CREATE TABLE voice_note_metadata(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES users(id)ON DELETE CASCADE,media_asset_id uuid NOT NULL UNIQUE REFERENCES media_assets(id)ON DELETE CASCADE,duration_seconds integer,language varchar(16),recorded_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version integer NOT NULL DEFAULT 1,CONSTRAINT ck_voice_duration CHECK(duration_seconds IS NULL OR duration_seconds BETWEEN 1 AND 3600))`,
    );
    await q.query(
      `CREATE TABLE sync_changes(sequence bigserial PRIMARY KEY,user_id uuid NOT NULL REFERENCES users(id)ON DELETE CASCADE,resource_type varchar(40)NOT NULL,resource_id uuid NOT NULL,operation varchar(16)NOT NULL,data jsonb NOT NULL,changed_at timestamptz NOT NULL DEFAULT now());CREATE INDEX idx_sync_changes_user_cursor ON sync_changes(user_id,sequence)`,
    );
    await q.query(
      `CREATE FUNCTION record_sync_change()RETURNS trigger LANGUAGE plpgsql AS $$DECLARE uid uuid;rtype text;safe jsonb;BEGIN CASE TG_TABLE_NAME WHEN 'farmer_tasks'THEN uid:=NEW.user_id;rtype:='TASK';safe:=jsonb_build_object('id',NEW.id,'fieldId',NEW.field_id,'title',NEW.title,'status',NEW.status,'dueAt',NEW.due_at,'version',NEW.version);WHEN 'field_inspections'THEN uid:=NEW.user_id;rtype:='FIELD_INSPECTION';safe:=jsonb_build_object('id',NEW.id,'fieldId',NEW.field_id,'notes',NEW.notes,'observedAt',NEW.observed_at,'mediaAssetIds',NEW.media_asset_ids,'version',NEW.version);WHEN 'voice_note_metadata'THEN uid:=NEW.user_id;rtype:='VOICE_NOTE';safe:=jsonb_build_object('id',NEW.id,'mediaAssetId',NEW.media_asset_id,'durationSeconds',NEW.duration_seconds,'language',NEW.language,'recordedAt',NEW.recorded_at,'version',NEW.version);WHEN 'crop_scans'THEN uid:=NEW.owner_id;rtype:='CROP_SCAN';safe:=jsonb_build_object('id',NEW.id,'fieldId',NEW.field_id,'status',NEW.status,'version',NEW.version);WHEN 'follow_up_answers'THEN uid:=NEW.farmer_id;rtype:='FOLLOW_UP_ANSWER';safe:=jsonb_build_object('id',NEW.id,'questionId',NEW.question_id,'answer',NEW.answer_text,'answeredAt',NEW.answered_at,'version',NEW.version);WHEN 'community_reports'THEN uid:=NEW.reporter_id;rtype:='COMMUNITY_REPORT';safe:=jsonb_build_object('id',NEW.id,'fieldId',NEW.field_id,'cropId',NEW.crop_id,'conditionFamily',NEW.condition_family,'source',NEW.source,'reportedAt',NEW.reported_at,'locationPrivacy','REGIONAL_ONLY');WHEN 'notifications'THEN uid:=NEW.user_id;rtype:='NOTIFICATION';safe:=jsonb_build_object('id',NEW.id,'category',NEW.category,'title',NEW.title,'body',NEW.body,'data',NEW.data,'readAt',NEW.read_at,'version',NEW.version);ELSE RETURN NEW;END CASE;INSERT INTO sync_changes(user_id,resource_type,resource_id,operation,data,changed_at)VALUES(uid,rtype,NEW.id,CASE WHEN TG_OP='INSERT'THEN'CREATED'ELSE'UPDATED'END,safe,now());RETURN NEW;END$$;CREATE TRIGGER sync_tasks AFTER INSERT OR UPDATE ON farmer_tasks FOR EACH ROW EXECUTE FUNCTION record_sync_change();CREATE TRIGGER sync_inspections AFTER INSERT OR UPDATE ON field_inspections FOR EACH ROW EXECUTE FUNCTION record_sync_change();CREATE TRIGGER sync_voice_notes AFTER INSERT OR UPDATE ON voice_note_metadata FOR EACH ROW EXECUTE FUNCTION record_sync_change();CREATE TRIGGER sync_crop_scans AFTER INSERT OR UPDATE ON crop_scans FOR EACH ROW EXECUTE FUNCTION record_sync_change();CREATE TRIGGER sync_follow_up_answers AFTER INSERT OR UPDATE ON follow_up_answers FOR EACH ROW EXECUTE FUNCTION record_sync_change();CREATE TRIGGER sync_community_reports AFTER INSERT OR UPDATE ON community_reports FOR EACH ROW EXECUTE FUNCTION record_sync_change();CREATE TRIGGER sync_notifications AFTER INSERT OR UPDATE ON notifications FOR EACH ROW EXECUTE FUNCTION record_sync_change()`,
    );
  }
  async down(q: QueryRunner): Promise<void> {
    await q.query(
      `DROP FUNCTION IF EXISTS record_sync_change CASCADE;DROP TABLE IF EXISTS sync_changes,voice_note_metadata,field_inspections,mutation_receipts CASCADE`,
    );
  }
}
