import { NextResponse, type NextRequest } from 'next/server';
const ACCESS_COOKIE = 'fg_access'; const REFRESH_COOKIE = 'fg_refresh'; const apiBase = () => (process.env.FASALGUARD_API_URL ?? 'http://localhost:4000/api/v1').replace(/\/$/, '');
type User = { role: string }; type Tokens = { accessToken: string; refreshToken: string; expiresIn: number };
async function currentUser(access?: string): Promise<User | null> { if (!access) return null; const response = await fetch(`${apiBase()}/auth/me`, { headers: { authorization: `Bearer ${access}` }, cache: 'no-store', signal: AbortSignal.timeout(8000) }); return response.ok ? ((await response.json()) as User) : null }
export async function proxy(request: NextRequest): Promise<NextResponse> {
  let access = request.cookies.get(ACCESS_COOKIE)?.value; const refresh = request.cookies.get(REFRESH_COOKIE)?.value; let user: User | null = null; let renewed: Tokens | null = null;
  try { user = await currentUser(access); if (!user && refresh) { const response = await fetch(`${apiBase()}/auth/refresh`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ refreshToken: refresh }), cache: 'no-store', signal: AbortSignal.timeout(8000) }); if (response.ok) { renewed = (await response.json()) as Tokens; access = renewed.accessToken; user = await currentUser(access) } } } catch { const login = new URL('/login', request.url); login.searchParams.set('reason', 'session-unavailable'); return NextResponse.redirect(login) }
  if (!user) { const login = new URL('/login', request.url); login.searchParams.set('returnTo', `${request.nextUrl.pathname}${request.nextUrl.search}`); const response = NextResponse.redirect(login); response.cookies.delete(ACCESS_COOKIE); response.cookies.delete(REFRESH_COOKIE); return response }
  const path = request.nextUrl.pathname; const allowed = path.startsWith('/expert') ? ['AGRICULTURE_EXPERT', 'ADMIN', 'SUPER_ADMIN'].includes(user.role) : path.startsWith('/government') ? ['GOVERNMENT_VIEWER', 'NGO_VIEWER', 'ADMIN', 'SUPER_ADMIN'].includes(user.role) : ['FARMER', 'FIELD_WORKER', 'ADMIN', 'SUPER_ADMIN'].includes(user.role);
  if (!allowed) return NextResponse.redirect(new URL(user.role === 'AGRICULTURE_EXPERT' ? '/expert' : ['GOVERNMENT_VIEWER', 'NGO_VIEWER'].includes(user.role) ? '/government' : '/dashboard', request.url));
  const response = NextResponse.next(); if (renewed) { const secure = process.env.NODE_ENV === 'production'; response.cookies.set(ACCESS_COOKIE, renewed.accessToken, { httpOnly: true, secure, sameSite: 'lax', path: '/', maxAge: renewed.expiresIn }); response.cookies.set(REFRESH_COOKIE, renewed.refreshToken, { httpOnly: true, secure, sameSite: 'lax', path: '/', maxAge: 30 * 86400 }) } return response;
}
export const config = { matcher: ['/dashboard/:path*', '/farms/:path*', '/fields/:path*', '/scan/:path*', '/satellite/:path*', '/weather/:path*', '/radar/:path*', '/alerts/:path*', '/tasks/:path*', '/consultations/:path*', '/assistant/:path*', '/learning/:path*', '/reports/:path*', '/analytics/:path*', '/settings/:path*', '/crop-health/:path*', '/expert/:path*', '/government/:path*'] };
