import Link from "next/link";

const mapUrl="https://lh3.googleusercontent.com/aida-public/AB6AXuCNcsIcrH4aQ_JfQgsqCZKg8V8gVJozmA5-d6k3y2AhD8D4QLLOs3zt99DKqOZtBYhWbcecXGPC1eYLa10IItNWMTmj7WOk6JBZrO4giVtDii3IQ9Hv1uaBV1NgBbp91X4FpfQP372diZfjHJeMuyUhZaA409cWq1Vxppjxs4nnH6tu_a2NboCu_svdSrXEj3F6N8414yN4XvP0ZNFno3-uJpLyMwEG4XSAT-8JuaSITkp6ApewvYy6";
const scanOne="https://lh3.googleusercontent.com/aida-public/AB6AXuCUwUPeD9jGWf34No-mjTuJM3NSOEQ1f6sHOU5LLfEJICXcIwXqbsfm6E9WXI8qxQL8nLhQTh-9gqwW4o2SPFiJ9MyCEJzN6pw9FUA-Z0zTMScJI0fwY35EOrEeHcpn1EaYDK4k8tcnzi09ls5b4BctoAy_mvsiQocFWVh4YcwLn2P0Pot_o6amWaRKX7gW25tiiDyaBFOlonmNHsNg2XX-mO1UWMj6h4e1TJEuMLXKEIwu6NJapOcu";
const scanTwo="https://lh3.googleusercontent.com/aida-public/AB6AXuA6jBsxHHRosgc5-46qll8COcaTaFsHQxKocej1mxQKA6cUCYc3L-my5mxtn6W68xrVorf1qOmWnrReZucX-8EVcSKREZJe26HGk5Sgmf1IECe0GDxSPNQB0dUgJlDWgNRS3eJ1y3LfU5k3FmiYAtZU4VEdykiuMU6ctNz1iVBB9HESAEcmfUiRidOY73suToALpx5EScO7lrR_LB_Xl3y5eWpeBxYGgH4JXXNZWm_IOZTMCOAAp1Op";

export function FarmerDashboard(){return <div className="mx-auto max-w-[1180px] p-4 md:p-6 xl:p-7"><header className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-[26px] font-extrabold leading-tight text-brand-dark">Good morning, Ahmad</h1><p className="mt-1 text-xs text-muted">Here is the latest health status of your farms.</p></div><div className="flex gap-2"><Link href="/farms/green-valley/fields" className="inline-flex min-h-10 items-center rounded-xl border border-brand px-4 text-xs font-extrabold text-brand">Add field</Link><Link href="/scan" className="inline-flex min-h-10 items-center rounded-xl bg-brand px-4 text-xs font-extrabold text-white">Scan crop</Link></div></header>
 <section className="grid grid-cols-2 gap-3 md:grid-cols-5"><Summary label="Active farms" value="2"/><Summary label="Active fields" value="5"/><Summary label="Avg. health" value="78%" ring/><Summary label="Nearby alerts" value="2" danger/><Summary label="Pending tasks" value="4"/></section>
 <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,2fr)_minmax(245px,.82fr)]"><div className="space-y-4"><section className="rounded-2xl border border-border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-sm font-extrabold">Field Health Overview</h2><Link href="/fields" className="text-[11px] font-bold text-brand">View all →</Link></div><div className="mt-4 hidden grid-cols-[1.2fr_.8fr_.8fr_.8fr_auto] gap-3 border-b border-border pb-2 text-[9px] font-extrabold uppercase tracking-wide text-muted sm:grid"><span>Field name</span><span>Crop</span><span>Health score</span><span>Risk</span><span>Action</span></div><div>{[{field:"North Field",crop:"Cotton",score:82,risk:"Low",color:"bg-success"},{field:"Canal Field",crop:"Wheat",score:61,risk:"Moderate",color:"bg-warning"},{field:"South Field",crop:"Cotton",score:43,risk:"High",color:"bg-danger"}].map(item=><div key={item.field} className="grid grid-cols-[1fr_auto] gap-3 border-b border-border py-3 text-xs last:border-0 sm:grid-cols-[1.2fr_.8fr_.8fr_.8fr_auto]"><div><strong>{item.field}</strong><p className="text-[10px] text-muted">Last scan recently</p></div><span className="hidden sm:block">{item.crop}</span><div className="hidden items-center gap-2 sm:flex"><span className="h-1.5 w-16 rounded bg-border"><span className={`block h-1.5 rounded ${item.color}`} style={{width:`${item.score}%`}}/></span><strong>{item.score}%</strong></div><span className="hidden sm:block">{item.risk}</span><Link href="/fields" className="font-bold text-brand">View</Link></div>)}</div></section>
 <section className="rounded-2xl bg-[#a96300] p-5 text-white shadow-sm"><div className="flex gap-4"><div className="grid size-10 shrink-0 place-items-center rounded-full bg-white/15 text-xl">!</div><div><p className="text-[10px] font-bold uppercase tracking-wider text-amber-100">Crop-aware weather alert</p><h2 className="mt-1 text-base font-extrabold">High humidity may increase cotton risk</h2><p className="mt-1 max-w-xl text-xs leading-5 text-white/80">Humidity may remain above 80% for 36 hours. Inspect younger leaves in North Field and avoid unnecessary irrigation.</p><div className="mt-4 flex flex-wrap gap-2"><Link href="/weather" className="rounded-lg bg-white/15 px-3 py-2 text-[11px] font-bold">View weather guidance</Link><Link href="/satellite" className="rounded-lg bg-white/15 px-3 py-2 text-[11px] font-bold">Check satellite zones</Link></div></div></div></section>
 <section className="overflow-hidden rounded-2xl border border-border bg-white shadow-sm"><div className="flex items-center justify-between p-4"><h2 className="text-sm font-extrabold">Farm Outbreak Radar</h2><div className="flex gap-3 text-[10px]"><span>● Safe</span><span className="text-warning">● Warning</span></div></div><div className="relative h-[370px] bg-cover bg-center" style={{backgroundImage:`url(${mapUrl})`}}><span className="absolute left-[49%] top-[53%] grid size-11 place-items-center rounded-full border-4 border-white bg-brand text-xs font-extrabold text-white shadow-xl">GF</span><span className="absolute left-[70%] top-[30%] size-5 rounded-full border-4 border-white bg-danger shadow"/><span className="absolute left-[22%] top-[46%] size-4 rounded-full border-4 border-white bg-info shadow"/><div className="absolute bottom-3 left-3 rounded-lg bg-white/90 px-3 py-2 text-[10px] font-bold shadow">Green Valley Farm · approximate location</div></div></section></div>
 <aside className="space-y-4"><section className="rounded-2xl border border-border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-sm font-extrabold">Today’s Tasks</h2><span className="grid size-6 place-items-center rounded-full bg-brand text-xs text-white">4</span></div><div className="mt-4 space-y-4">{["Inspect young cotton plants","Upload follow-up image","Review expert message","Check irrigation status"].map((task,index)=><label key={task} className="flex gap-3 text-xs leading-5"><input type="checkbox" className="mt-0.5 size-4 accent-brand" defaultChecked={index===3}/><span>{task}<small className="block text-[9px] text-muted">{index<2?"Due today":"This week"}</small></span></label>)}</div></section>
 <section className="rounded-2xl border border-border bg-white p-5 shadow-sm"><h2 className="text-sm font-extrabold">Recent AI Scans</h2><div className="mt-4 space-y-3"><Scan image={scanOne} title="Leaf Curl" field="North Field" status="Review"/><Scan image={scanTwo} title="Healthy" field="Canal Field" status="Good"/></div><Link href="/scan/results" className="mt-4 block text-center text-[11px] font-bold text-brand">View all scans</Link></section>
 <section className="rounded-2xl border border-border bg-white p-5 shadow-sm"><h2 className="text-sm font-extrabold">7-Day Risk Forecast</h2><div className="mt-5 flex h-36 items-end justify-between gap-2">{[{d:"Mon",v:35,c:"bg-success"},{d:"Tue",v:48,c:"bg-success"},{d:"Wed",v:62,c:"bg-info"},{d:"Thu",v:78,c:"bg-warning"},{d:"Fri",v:92,c:"bg-danger"},{d:"Sat",v:83,c:"bg-danger"}].map(x=><div key={x.d} className="flex flex-1 flex-col items-center justify-end gap-2"><span className={`w-2.5 rounded-full ${x.c}`} style={{height:`${x.v}px`}}/><span className="text-[9px] font-bold text-muted">{x.d}</span></div>)}</div><div className="mt-4 grid grid-cols-3 border-t border-border pt-3 text-center"><Small label="Humidity" value="72%"/><Small label="Rain" value="20%"/><Small label="Risk" value="High"/></div></section></aside></div></div>}
function Summary({label,value,ring,danger}:{label:string;value:string;ring?:boolean;danger?:boolean}){return <div className={`rounded-2xl border p-4 shadow-sm ${danger?"border-red-100 bg-red-50":"border-border bg-white"}`}><p className="text-[10px] font-bold text-muted">{label}</p>{ring?<div className="mt-2 grid size-14 place-items-center rounded-full border-[6px] border-brand-soft border-t-brand text-sm font-extrabold">{value}</div>:<p className={`mt-4 text-2xl font-extrabold ${danger?"text-danger":"text-brand-dark"}`}>{value}</p>}</div>}
function Scan({image,title,field,status}:{image:string;title:string;field:string;status:string}){return <div className="flex gap-3 rounded-xl bg-surface-soft p-2"><div className="size-14 shrink-0 rounded-lg bg-cover bg-center" style={{backgroundImage:`url(${image})`}} role="img" aria-label={`${title} crop scan`}/><div className="min-w-0 flex-1"><div className="flex justify-between"><strong className="text-xs">{title}</strong><span className="rounded bg-brand-soft px-1.5 py-0.5 text-[8px] font-bold text-brand">{status}</span></div><p className="mt-1 text-[10px] text-muted">{field}</p><p className="mt-1 text-[9px] text-muted">AI screening result</p></div></div>}
function Small({label,value}:{label:string;value:string}){return <div><p className="text-[8px] uppercase text-muted">{label}</p><strong className="text-[10px]">{value}</strong></div>}
