"use client";

import Link from "next/link";
import {useState} from "react";

const plans={"Immediate Actions":["Inspect neighboring plants","Whitefly population count","Isolate affected zone"],"Next 48 Hours":["Record whether symptoms spread","Upload a follow-up image","Request expert verification"],Prevention:["Use tolerant seed where advised","Control alternate host weeds","Clean tools between field zones"]};

export function HealthAssessment(){
 const [tab,setTab]=useState<keyof typeof plans>("Immediate Actions");
 return <div className="mx-auto max-w-[1120px] space-y-5 px-4 py-5 md:px-6 md:py-7">
  <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex gap-2"><span className="rounded-full bg-brand-soft px-3 py-1 text-[9px] font-extrabold uppercase text-brand">AI assessment result</span><span className="rounded-full border border-brand/15 bg-white px-3 py-1 text-[9px] font-bold">ID: FG-98441</span></div><h1 className="mt-3 text-2xl font-extrabold text-brand-dark">Crop Health Assessment</h1><p className="mt-1 text-[10px] text-muted">AI Result</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>window.print()} className="min-h-10 rounded-full border border-brand/15 bg-white px-4 text-xs font-extrabold">⇩ Download Report</button><button aria-label="Share report" className="grid size-10 place-items-center rounded-full border border-brand/15 bg-white">↗</button><Link href="/consultations" className="inline-flex min-h-10 items-center rounded-full bg-brand px-5 text-xs font-extrabold text-white">▣ Request Expert Review</Link></div></header>
  <section className="grid gap-4 lg:grid-cols-[2.15fr_.9fr]">
   <article className="grid overflow-hidden rounded-2xl border border-brand/10 bg-white shadow-sm sm:grid-cols-[14rem_1fr]"><div className="relative min-h-64 bg-[radial-gradient(ellipse_at_center,#bbd882_0_18%,transparent_19%),linear-gradient(140deg,#315e2f,#91b66b)]"><div className="absolute inset-x-3 bottom-3 rounded-lg bg-black/55 px-3 py-2 text-[9px] text-white">Visual markers: leaf curl · vein thickening</div></div><div className="p-5"><p className="text-[9px] font-extrabold uppercase tracking-wide text-warning">⚠ High severity detected</p><h2 className="mt-2 text-xl font-extrabold text-brand-dark">Cotton Leaf Curl Disease</h2><p className="mt-3 text-xs leading-5 text-muted">The AI model has identified significant structural abnormalities in the leaf morphology that strongly correspond with CLCuD viral infection patterns.</p><div className="mt-4 flex gap-3"><div className="rounded-xl bg-[#edf6e9] px-4 py-3"><p className="text-[8px] font-bold uppercase text-muted">AI Confidence</p><strong className="text-2xl text-brand-dark">86%</strong><span className="ml-1 text-[9px] text-success">Healthy</span></div><div className="rounded-xl bg-amber-50 px-4 py-3"><p className="text-[8px] font-bold uppercase text-muted">Severity</p><strong className="mt-1 block text-xs text-amber-900">● Review Req.</strong></div></div><p className="mt-4 rounded-xl bg-[#eef4ff] p-3 text-[10px] leading-4 text-[#315275]">ⓘ Disclaimer: This is an AI-assisted screening result and not a laboratory-confirmed diagnosis. Expert review is recommended before taking chemical action.</p></div></article>
   <aside className="rounded-2xl border border-brand/10 bg-white p-5 shadow-sm"><div className="flex justify-between"><h2 className="text-sm font-extrabold">Health History</h2><span>◷</span></div><ol className="mt-5 space-y-5 border-l border-border pl-5"><Timeline color="bg-brand" date="8 Aug · Current" title="Severity: High" text="Expert review requested for leaf curl."/><Timeline color="bg-amber-400" date="29 Jul" title="Severity: Medium" text="Initial curling symptoms recorded."/><Timeline color="bg-green-500" date="14 Jul" title="Normal Baseline" text="Regular observation, no issues."/></ol></aside>
  </section>
  <section className="grid gap-4 lg:grid-cols-[.85fr_1.65fr]"><article className="rounded-2xl border border-brand/10 bg-white p-5 shadow-sm"><h2 className="text-sm font-extrabold">◉ &nbsp;Detected Symptoms</h2><ul className="mt-4 space-y-3">{[["Leaf curling","Primary"],["Yellow vein pattern","Mild"],["Reduced leaf size",""],["Irregular leaf texture",""]].map(([name,badge])=><li key={name} className="flex items-center justify-between rounded-xl bg-[#f7f7fb] px-4 py-3 text-xs"><span><b className="mr-3 text-amber-500">●</b>{name}</span>{badge&&<span className="rounded-full bg-white px-2 py-1 text-[8px] font-bold text-muted">{badge}</span>}</li>)}</ul></article><article className="rounded-2xl border border-brand/10 bg-white p-5 shadow-sm"><h2 className="text-sm font-extrabold">♙ &nbsp;AI Diagnostic Reasoning</h2><p className="mt-4 text-xs leading-5 text-muted">The AI cross-referenced uploaded imagery with its visual database of over 50,000 cotton plant pathology samples. The specific combination of upward-curling, thickened veins and stunted morphology strongly indicates viral stress. Farmer reports of increased whitefly activity in the area have also been factored into the diagnostic weight.</p><h3 className="mt-5 text-[9px] font-extrabold uppercase text-brand">Alternative possibilities</h3><ul className="mt-3 space-y-3"><Alternative label="Whitefly-related damage" value="11%"/><Alternative label="Nutrient stress (Mg)" value="7%"/><Alternative label="Heat stress" value="4%"/></ul></article></section>
  <section className="grid gap-4 lg:grid-cols-[.9fr_2fr]"><article className="rounded-2xl border border-brand/10 bg-white p-5 shadow-sm"><h2 className="text-sm font-extrabold">Severity Breakdown</h2><div className="mx-auto mt-5 grid size-32 place-items-center rounded-full border-[8px] border-amber-400 border-l-brand-soft text-center"><div><strong className="block text-2xl text-warning">High</strong><span className="text-[9px] text-muted">Total risk score</span></div></div><dl className="mt-5 space-y-3 text-[10px]"><Bar label="Visual Symptoms" value="88%"/><Bar label="Environmental Context" value="64%"/><Bar label="Community Reports" value="42%"/></dl></article><article className="overflow-hidden rounded-2xl border border-brand/10 bg-white shadow-sm"><div role="tablist" className="flex border-b border-border">{Object.keys(plans).map(key=><button key={key} onClick={()=>setTab(key as keyof typeof plans)} className={`min-h-12 flex-1 px-3 text-[10px] font-extrabold ${tab===key?"border-b-2 border-brand text-brand":"text-muted"}`}>{key}</button>)}</div><ol className="space-y-3 p-5">{plans[tab].map((item,index)=><li key={item} className="flex gap-3 rounded-xl px-2 py-2 text-xs"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-brand-soft font-bold text-brand">{index===0?"⌕":index===1?"◉":"△"}</span><span><strong className="block">{item}</strong><small className="text-[9px] text-muted">Follow locally appropriate guidance and record your observations.</small></span></li>)}</ol><Link href="/radar" className="flex items-center gap-3 border-t border-border bg-[#edf6e9] p-4 text-[10px] font-bold text-brand"><span className="grid size-7 place-items-center rounded-full bg-white">✓</span>Contribute to Outbreak Map <span className="font-normal text-muted">Anonymous approximate-area report</span></Link></article></section>
 </div>
}
function Timeline({date,title,text,color}:{date:string;title:string;text:string;color:string}){return <li className="relative before:absolute before:-left-[25px] before:top-1 before:size-3 before:rounded-full before:bg-current"><span className={`absolute -left-[25px] top-1 size-3 rounded-full ${color}`}/><p className="text-[8px] font-bold text-muted">{date}</p><p className="mt-1 text-xs font-extrabold">{title}</p><p className="mt-1 text-[9px] leading-4 text-muted">{text}</p></li>}
function Alternative({label,value}:{label:string;value:string}){return <li className="flex items-center gap-3 text-[10px]"><span className="w-36 font-semibold">{label}</span><span className="h-1.5 flex-1 rounded-full bg-surface-soft"><span className="block h-full rounded-full bg-brand" style={{width:value}}/></span><strong>{value}</strong></li>}
function Bar({label,value}:{label:string;value:string}){return <div><div className="flex justify-between"><dt>{label}</dt><dd className="font-bold">{value}</dd></div><div className="mt-1 h-1 rounded-full bg-surface-soft"><div className="h-full rounded-full bg-brand" style={{width:value}}/></div></div>}
