"use client";

import Link from "next/link";
import {useMemo,useState} from "react";
import {outbreakClusters} from "@/features/outbreaks/data";
import type {OutbreakCluster} from "@/features/outbreaks/types";

const statusLabels={monitoring:"Monitoring",suspected:"Suspected",community_supported:"Community supported",expert_confirmed:"Expert confirmed"};

export function OutbreakRadar(){
 const [crop,setCrop]=useState("Cotton");const [selectedId,setSelectedId]=useState(outbreakClusters[0]?.id);const [subscribed,setSubscribed]=useState(false);const [distance,setDistance]=useState(15);const [verification,setVerification]=useState("All Reports");
 const clusters=useMemo(()=>crop==="All crops"?outbreakClusters:outbreakClusters.filter(item=>item.crop===crop),[crop]);const selected=clusters.find(item=>item.id===selectedId)??clusters[0]??outbreakClusters[0];
 function exportData(){const rows=["Disease,District,Status,Reports",...clusters.map(c=>`${c.disease},${c.district},${c.status},${c.reportCount}`)];const url=URL.createObjectURL(new Blob([rows.join("\n")],{type:"text/csv"}));const anchor=document.createElement("a");anchor.href=url;anchor.download="fasalguard-outbreak-radar.csv";anchor.click();URL.revokeObjectURL(url)}
 async function share(){if(navigator.share)await navigator.share({title:"FasalGuard outbreak radar",text:"Privacy-protected crop disease monitoring report"});else await navigator.clipboard?.writeText(window.location.href)}
 return <div className="mx-auto max-w-[1240px] space-y-5 px-4 py-5 md:px-6 md:py-7">
  <header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h1 className="text-2xl font-extrabold text-brand-dark md:text-3xl">Crop Disease Outbreak Radar</h1><p className="mt-1 text-xs text-muted md:text-sm">Monitor suspected and confirmed crop health threats across nearby regions.</p></div><div className="flex gap-2"><button onClick={exportData} className="min-h-10 rounded-xl border border-brand/15 bg-white px-4 text-xs font-extrabold text-brand">⇩ Export Data</button><button onClick={()=>void share()} className="min-h-10 rounded-xl bg-brand px-4 text-xs font-extrabold text-white">↗ Share Report</button></div></header>
  <section className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Stat icon="⌁" label="Active Clusters" value="07" note="+2 since yesterday"/><Stat icon="⚠" label="Confirmed Outbreaks" value="02" note="High Priority District" danger/><Stat icon="◖" label="Farmers Alerted" value="186" note="94% Read Rate"/><Stat icon="◉" label="High-Risk Districts" value="03" note="Critical Vigilance" warning/></section>
  <section className="grid gap-4 xl:grid-cols-[15rem_minmax(0,1fr)_18rem]">
   <aside className="h-fit rounded-2xl border border-brand/10 bg-white p-5 shadow-sm"><div className="flex justify-between"><h2 className="text-sm font-extrabold">Filters</h2><button onClick={()=>{setCrop("Cotton");setDistance(15);setVerification("All Reports")}} className="text-[9px] font-bold text-brand">Reset All</button></div><FilterLabel>Crop Type</FilterLabel><div className="flex flex-wrap gap-2">{["Cotton","Wheat","All crops"].map(item=><button key={item} onClick={()=>setCrop(item)} className={`rounded-full px-3 py-1.5 text-[9px] font-bold ${crop===item?"bg-brand text-white":"border border-brand/15 text-muted"}`}>{item}</button>)}</div><FilterLabel>Province</FilterLabel><select className="h-10 w-full rounded-xl border border-brand/10 bg-[#eef4ff] px-3 text-xs"><option>Punjab</option><option>Sindh</option><option>Khyber Pakhtunkhwa</option></select><FilterLabel>Risk Level</FilterLabel><div className="space-y-2 text-[10px]"><Check color="accent-danger" label="Confirmed Outbreak" defaultChecked/><Check color="accent-amber-700" label="High Risk" defaultChecked/><Check color="accent-brand" label="Suspected"/></div><FilterLabel>Distance From My Farms <span className="float-right text-brand">{distance}km</span></FilterLabel><input type="range" min="0" max="100" value={distance} onChange={e=>setDistance(Number(e.target.value))} className="w-full accent-brand"/><div className="flex justify-between text-[8px] text-muted"><span>0km</span><span>100km</span></div><FilterLabel>Verification Status</FilterLabel><div className="space-y-1">{["All Reports","Expert Verified Only","AI Detected Only"].map(item=><button key={item} onClick={()=>setVerification(item)} className={`w-full rounded-lg px-3 py-2 text-left text-[9px] font-bold ${verification===item?"bg-[#edf6e9] text-brand":"hover:bg-surface-soft"}`}>{item}</button>)}</div><p className="mt-5 rounded-xl bg-surface-soft p-3 text-[9px] leading-4 text-muted">Exact farm coordinates are displaced and grouped to protect farmer privacy.</p></aside>
   <section aria-label="Privacy-protected outbreak map" className="relative min-h-[560px] overflow-hidden rounded-2xl border border-brand/10 bg-[#e8ece5] shadow-inner"><div className="absolute inset-0 opacity-75 [background-image:linear-gradient(25deg,transparent_47%,rgba(45,105,77,.15)_48%,transparent_49%),linear-gradient(115deg,transparent_46%,rgba(45,105,77,.1)_47%,transparent_48%),radial-gradient(circle_at_30%_40%,#f3ead7,#dce6dc_60%,#cbd9d0)] [background-size:85px_70px,110px_95px,100%_100%]"/><span className="absolute left-[36%] top-[25%] h-44 w-44 -translate-x-1/2 -translate-y-1/2 rounded-full bg-red-500/20 blur-xl"/><span className="absolute left-[67%] top-[58%] h-48 w-48 -translate-x-1/2 -translate-y-1/2 rounded-full bg-amber-400/20 blur-xl"/>{clusters.map((cluster,index)=><button key={cluster.id} onClick={()=>setSelectedId(cluster.id)} style={{left:`${cluster.position.x}%`,top:`${cluster.position.y}%`}} className={`absolute z-10 -translate-x-1/2 -translate-y-1/2 font-extrabold shadow-lg transition-transform hover:scale-110 ${cluster.status==="expert_confirmed"?"grid size-12 place-items-center rounded-full border border-danger bg-danger/20 text-danger":cluster.risk==="high"?"rounded-full border border-amber-700 bg-amber-400 px-3 py-1.5 text-[9px] text-amber-950":"grid size-5 place-items-center rounded-full border-2 border-white bg-brand text-[7px] text-white"}`}>{cluster.status==="expert_confirmed"?"!":index===0?`${cluster.reportCount} Reports`:cluster.reportCount}</button>)}<div className="absolute right-4 top-4 z-10 flex flex-col gap-2"><MapButton>+</MapButton><MapButton>−</MapButton><MapButton>▱</MapButton></div><div className="absolute bottom-4 left-4 z-10 rounded-xl border border-brand/10 bg-white/90 p-3 text-[8px] shadow-lg backdrop-blur"><strong className="uppercase tracking-wide text-muted">Map Legend</strong><p className="mt-2 space-x-2"><span className="text-green-700">● Monitoring</span><span className="text-amber-500">● Suspected</span></p><p className="mt-1 space-x-2"><span className="text-amber-800">● High Risk</span><span className="text-danger">● Confirmed</span></p><p className="mt-1 text-brand">● My Farms</p></div><span className="absolute left-[42%] top-[59%] z-10 grid size-5 place-items-center rounded-full border-2 border-white bg-brand text-[7px] text-white shadow">GF</span></section>
   <aside className="overflow-hidden rounded-2xl border border-brand/10 bg-white shadow-sm">{selected?<ClusterDetails cluster={selected} subscribed={subscribed} onSubscribe={()=>setSubscribed(!subscribed)}/>:<p className="p-5 text-xs text-muted">No clusters match the filters.</p>}</aside>
  </section>
  <Link href="/alerts#community-report" className="fixed bottom-24 right-5 z-20 inline-flex min-h-12 items-center rounded-full bg-danger px-5 text-xs font-extrabold text-white shadow-xl lg:bottom-7">⚠ Report New Outbreak</Link>
 </div>
}
function Stat({icon,label,value,note,danger,warning}:{icon:string;label:string;value:string;note:string;danger?:boolean;warning?:boolean}){return <article className={`rounded-2xl border bg-white p-4 shadow-sm ${danger?"border-l-4 border-red-500":warning?"border-l-4 border-amber-700":"border-brand/10"}`}><span className={danger?"text-danger":warning?"text-amber-800":"text-success"}>{icon}</span><p className="mt-2 text-[8px] font-extrabold uppercase tracking-wider text-muted">{label}</p><p className={`text-2xl font-extrabold ${danger?"text-danger":warning?"text-amber-800":"text-brand-dark"}`}>{value}</p><p className={`mt-1 text-[8px] font-bold ${danger?"text-danger":warning?"text-amber-800":"text-success"}`}>{note}</p></article>}
function FilterLabel({children}:{children:React.ReactNode}){return <p className="mb-2 mt-5 text-[8px] font-extrabold uppercase tracking-wider text-muted">{children}</p>}
function Check({label,color,defaultChecked}:{label:string;color:string;defaultChecked?:boolean}){return <label className="flex items-center gap-2"><input type="checkbox" defaultChecked={defaultChecked} className={`size-3.5 rounded ${color}`}/>{label}</label>}
function MapButton({children}:{children:React.ReactNode}){return <button className="grid size-9 place-items-center rounded-xl border border-brand/10 bg-white text-lg font-bold shadow">{children}</button>}
function ClusterDetails({cluster,subscribed,onSubscribe}:{cluster:OutbreakCluster;subscribed:boolean;onSubscribe:()=>void}){return <div className="flex h-full flex-col"><div className="border-b border-brand/10 bg-[#edf6e9]/60 p-5"><div className="flex items-start justify-between gap-2"><h2 className="text-sm font-extrabold leading-5">{cluster.disease} —<br/>{cluster.district}</h2><span className="rounded bg-amber-300 px-2 py-1 text-[7px] font-extrabold text-amber-950">{statusLabels[cluster.status].toUpperCase()}</span></div><dl className="mt-4 grid grid-cols-2 gap-3"><MiniMetric label="Reports" value={cluster.reportCount}/><MiniMetric label="Expert Confirmed" value={cluster.expertConfirmedCount}/></dl></div><div className="flex-1 space-y-5 p-5"><div className="flex items-center justify-between rounded-xl border border-amber-800/10 bg-amber-50 p-3 text-[9px] font-extrabold text-amber-900"><span>⚠ Risk Level: {cluster.risk}</span><span>R: {cluster.radiusKm}km</span></div><div><div className="flex justify-between text-[8px] font-bold"><span>14-Day Report Trend</span><span className="text-success">+12%</span></div><svg viewBox="0 0 100 35" className="mt-2 h-14 w-full rounded-lg bg-[#eef4ff]"><path d="M0 30 Q20 27 35 18 T60 20 T80 8 T100 4" fill="none" stroke="#2d694d" strokeWidth="2"/></svg></div><div><h3 className="text-[8px] font-extrabold uppercase tracking-wider">Incident Timeline</h3><ol className="mt-4 space-y-4 border-l border-brand/15 pl-4"><Time title="First Report" text="Oct 12, 08:45 AM"/><Time title="Similar Reports" text={`${cluster.reportCount} reports within ${cluster.radiusKm}km`}/><Time title="Cluster Created" text="Automated analysis active"/><Time title="Expert Review Pending" text="Assigned to agriculture expert" muted/></ol></div></div><div className="space-y-2 border-t border-brand/10 p-5"><button className="min-h-10 w-full rounded-xl bg-brand text-[10px] font-extrabold text-white">◉ View Reports</button><div className="grid grid-cols-2 gap-2"><Link href="/fields" className="grid min-h-9 place-items-center rounded-xl border border-brand/15 text-[8px] font-bold text-brand">Inspect Field</Link><Link href="/learning" className="grid min-h-9 place-items-center rounded-xl border border-brand/15 text-[8px] font-bold text-brand">Prevention Guide</Link></div><button onClick={onSubscribe} className="min-h-9 w-full text-[9px] font-extrabold text-success">{subscribed?"✓ Alerts subscribed":"Subscribe to Alerts"}</button></div></div>}
function MiniMetric({label,value}:{label:string;value:string|number}){return <div><dt className="text-[7px] font-bold uppercase text-muted">{label}</dt><dd className="mt-1 text-xl font-extrabold text-brand-dark">{value}</dd></div>}
function Time({title,text,muted}:{title:string;text:string;muted?:boolean}){return <li className={`relative before:absolute before:-left-[21px] before:top-0.5 before:size-2.5 before:rounded-full before:bg-brand ${muted?"opacity-55":""}`}><strong className="block text-[9px]">{title}</strong><span className="text-[8px] text-muted">{text}</span></li>}
