"use client";

import Link from "next/link";
import { useState } from "react";
import { Icon } from "@/components/ui/icon";
import { satelliteZones } from "@/features/intelligence/data";

const farmMap = "https://lh3.googleusercontent.com/aida-public/AB6AXuDDxEDBr5GTTcxstYgfmN1hprMnPhJdHeq0HiGSKTsvDV4RTBXaUiPQP7hgs7lwAlHmuPC4iUa3yufxnKzXcEeQDB6-yNJpTVwrRo--BH7_gCLa-wbilBPcFV75nVslDd5e-SH65Nv8ZRs3m-nqx_kNo85Fjhvl5cDh3DnA6ATgY_qZUiROn5foY1uZAGbCoaSB6u-Dz7RjxOr1PxEzctuj7U_48uzIUyungpMmgzPBbyb-HshgUVIl";
const layers = ["True colour", "Crop health", "Vegetation", "Moisture stress", "Change detection"] as const;

export function SatelliteWorkspace() {
  const [layer, setLayer] = useState<(typeof layers)[number]>("Crop health");
  const [selected, setSelected] = useState(satelliteZones[0]);
  return <div className="page-container space-y-5">
    <header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.16em] text-success"><Icon name="satellite" className="size-4"/>Satellite intelligence</p><h1 className="mt-2 text-3xl font-extrabold text-brand-dark">Farm health monitoring</h1><p className="mt-2 max-w-3xl text-sm text-muted">Track field-level vegetation, moisture and change patterns. Ground inspection is required to determine the exact cause.</p></div><div className="flex flex-wrap gap-2"><button className="min-h-11 rounded-xl border border-border bg-white px-4 text-xs font-bold">Compare dates</button><button className="min-h-11 rounded-xl bg-brand px-4 text-xs font-extrabold text-white">Request latest scan</button></div></header>
    <section className="card grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-4"><Select label="Farm" value="Green Valley Farm"/><Select label="Field" value="North Field · Cotton"/><Select label="Capture" value="30 Jul 2026"/><Select label="Cloud filter" value="Below 15%"/></section>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_340px]">
      <section className="overflow-hidden rounded-[20px] border border-brand/10 bg-white shadow-[0_18px_50px_rgba(11,81,55,.09)]"><div className="flex gap-2 overflow-x-auto border-b border-border p-3">{layers.map(item=><button key={item} onClick={()=>setLayer(item)} className={`min-h-10 whitespace-nowrap rounded-xl px-4 text-xs font-bold ${layer===item?"bg-brand text-white":"bg-surface-soft text-muted"}`}>{item}</button>)}</div><div className="relative h-[440px] bg-cover bg-center sm:h-[560px]" style={{backgroundImage:`url(${farmMap})`}}><div className={`absolute inset-0 ${layer==="Crop health"?"bg-emerald-500/10":layer==="Moisture stress"?"bg-blue-500/10":layer==="Change detection"?"bg-amber-500/10":""}`}/><svg className="absolute inset-0 size-full" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><polygon points="12,20 78,12 92,72 62,90 16,76" fill="rgba(11,81,55,.08)" stroke="#f8fff9" strokeWidth="1" strokeDasharray="2 1"/></svg>{satelliteZones.map(zone=><button key={zone.id} onClick={()=>setSelected(zone)} style={{left:`${zone.left}%`,top:`${zone.top}%`}} className={`absolute -translate-x-1/2 -translate-y-1/2 rounded-full border-4 border-white shadow-xl transition hover:scale-110 ${zone.status==="high-stress"?"size-11 bg-danger":zone.status==="watch"?"size-10 bg-warning":"size-9 bg-success"}`} aria-label={`Select ${zone.name}`}><span className="sr-only">{zone.name}</span></button>)}<div className="absolute bottom-4 left-4 rounded-xl bg-white/95 p-3 text-[10px] shadow-xl"><strong>{layer}</strong><div className="mt-2 flex flex-wrap gap-3"><span className="text-success">● Healthy</span><span className="text-warning">● Watch</span><span className="text-danger">● High stress</span></div></div><div className="absolute right-4 top-4 grid gap-2"><button aria-label="Zoom in" className="grid size-11 place-items-center rounded-xl bg-white font-bold shadow">+</button><button aria-label="Zoom out" className="grid size-11 place-items-center rounded-xl bg-white font-bold shadow">−</button></div></div></section>
      <aside className="space-y-4"><section className="rounded-[20px] bg-brand p-5 text-white shadow-lg"><p className="text-[10px] font-bold uppercase tracking-wider text-white/65">Selected observation</p><h2 className="mt-2 text-xl font-extrabold">{selected.name}</h2><p className="mt-2 text-sm leading-6 text-white/80">Satellite data detected reduced vegetation activity in this zone.</p><dl className="mt-5 grid grid-cols-2 gap-3"><Metric label="Area" value={`${selected.areaAcres} ac`}/><Metric label="Change" value={`${selected.changePercent}%`}/><Metric label="Capture" value="30 Jul"/><Metric label="Cloud" value="8%"/></dl></section><section className="card p-5"><div className="flex items-center justify-between"><h2 className="font-extrabold">AI interpretation</h2><span className="rounded-full bg-brand-soft px-2.5 py-1 text-[9px] font-bold text-brand">82% signal quality</span></div><p className="mt-3 text-sm leading-6 text-muted">Vegetation activity decreased by 12% in the north-west section compared with the previous clear scan.</p><div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-900"><strong>Important limitation:</strong> this may reflect water, nutrient, pest or crop-health stress. Satellite imagery does not confirm a disease.</div></section><section className="card p-5"><h2 className="font-extrabold">Recommended next steps</h2><div className="mt-4 grid gap-2"><Action href="/tasks" label="Create inspection task"/><Action href="/scan" label="Upload ground-level photo"/><Action href="/assistant" label="Ask AI assistant"/><Action href="/consultations" label="Request expert review"/></div></section></aside>
    </div>
  </div>;
}
function Select({label,value}:{label:string;value:string}){return <label className="text-[10px] font-bold uppercase tracking-wider text-muted">{label}<select className="mt-2 h-11 w-full rounded-xl border border-border bg-surface-soft px-3 text-sm font-semibold normal-case tracking-normal text-foreground" defaultValue={value}><option>{value}</option></select></label>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-white/10 p-3"><dt className="text-[9px] text-white/60">{label}</dt><dd className="mt-1 text-sm font-extrabold">{value}</dd></div>}
function Action({href,label}:{href:string;label:string}){return <Link href={href} className="flex min-h-11 items-center justify-between rounded-xl bg-surface-soft px-4 text-xs font-bold text-brand-dark"><span>{label}</span><span aria-hidden>→</span></Link>}
